version: "3.3"

services:
  web:
    image: tomcat:9.0
    build: .
    container_name: mir-tomcat-rest
    ports:
      - "8080:8080"
    depends_on:
      - restdb
  restdb:
    container_name: mir-h2-database-rest
    hostname: h2-database-rest
    image: nkonev/h2:1.4.200
    volumes:
      - ./src/main/resources/dbForDockerScript.sql:/docker-entrypoint-initdb.d/dbForDockerScript.sql
    ports:
      - "9092:9092"
      - "8082:8082"
    restart: "no"
  client:
    build: ../restapi_test_client
    depends_on:
      - web