version: '3.3'
services:
  web:
    image: tomcat:9.0
    container_name: mirzoiev-tomcat
    ports:
      - 8080:8080
    depends_on:
      - db
    build: .

  db:
    image: nkonev/h2:1.4.200
    container_name: mirzoiev-db
    hostname: h2-database
    restart: "no"
    volumes:
       - ./dockerScript.sql:/docker-entrypoint-initdb.d/dockerScript.sql